version: "3.7"

services:
  api:
    build: .
    restart: always
    container_name: api
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
    networks:
      - node_network

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql-121
    volumes:
      - ./.data/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ticketBooking
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    networks:
      - node_network

networks:
  node_network:
    driver: bridge
